# This docker-compose file is based on example: https://geshan.com.np/blog/2021/12/docker-postgres/
# You may run it using `docker-compose -f docker-compose.yaml up`
# If port 5432 is in use run the following: `sudo lsof -i :5432` and `sudo kill -9 <pid>`

version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:17.0
    environment:
      - POSTGRES_USER=mydb
      - POSTGRES_PASSWORD=testpass123
      - POSTGRES_DB=postgres
    ports:
      - 6500:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
